contracts = [
    "fixed-weight-pool",
    "faucet",
    "alex-launchpad",
    "alex-vault",
    "fwp-wstx-usda-50-50",
    "fwp-wstx-wbtc-50-50",
    "multisig-fwp-wstx-wbtc-50-50",
    "multisig-fwp-wstx-usda-50-50",
    "multisig-crp-usda-wbtc",
    "collateral-rebalancing-pool"
]
